### ISSUE TITLE
Add URLs for each listed mod in each masterlist

### ISSUE THREAD

**Issue by CurusKeel** [loot/loot.github.io#31]
The recently introduced mod URL feature of LOOT is brilliant: people may forget what ESPs are linked to what mods sometimes, and this helps users keep better track of their mod list. I suggest that every listed mod in each masterlist (whenever possible) have URLs that link back to the original mod page.

For Fallout: New Vegas, I have started the move by making a pull request for adding URLs to a few mods (see loot/falloutnv#12 for the actual request). I suggest a push towards the other current masterlist repos too.

**Comment by Freso** [comment]
@William-Imm and @loot/looters: Do we still need this ticket open? Consider also discussion at #38.

**Comment by WrinklyNinja** [comment]
> This makes me ponder though, should we consider it advisable to add masterlist entries for only the sake of a link if the opportunity presents itself?

After further thought, I'm OK with this, but I'll stop short of making it a recommendation, i.e. you can add entries just to add a URL, or you can choose not to, and both are equally fine.

> Would it be possible to add a Nexus query-type tool to LOOT, that adds a dynamic link to all mods in the load order, which could open a browser and auto-search for the mod on the nexus? (Though I guess this would only be helpful if the esp name closely matched the mod name... so maybe not that useful after all.)

I'm going to shoot this down as not being worth the complexity, both in terms of effort saved and the accuracy of the results.

> @William-Imm and @loot/looters: Do we still need this ticket open? Consider also discussion at #38.

With my answers above, I have nothing more to add, but since @William-Imm opened it, I'll leave closing it to him.

**Comment by William-Imm** [comment]
I think I'll keep the ticket open. Still think it's good as a reminder to add mod URLs.

**Comment by Freso** [comment]
Wouldn't it be better to add a reminder in the documentation somewhere? (Possibly with a link/footnote link to this issue.)

**Comment by WrinklyNinja** [comment]
I've changed my mind on adding entries with only url metadata, as I'm currently trying to replace or remove dead links that have been reported, and it's a pain.

While being able to link plugins back to their mods' hosting location is useful to users, I strongly suspect that most use the Steam Workshop, Mod Organiser or Nexus Mod Manager, all of which strongly tie back to hosts (MO and NMM can show which mod an installed plugin is from, then where that mod was downloaded from). As such, the utility of LOOT including similar functionality is limited.

The URLs are still unquestionably useful for masterlist maintenance though, so adding a URL to entries with other metadata is a good idea.

**Comment by Freso** [comment]
My comment was more directed at the incredibly broad stated scope of the issue: add `url` entries to all mods in all the masterlists. This is a pretty monumental task, and I don't think any one volunteer will go and do all entries in all masterlists at one time. If we really want a "Add URLs for each listed mod" issue, I would suggest making one in the respective masterlist issue trackers, instead of having a global one here. Or, y'know, as I said: add a reminder/note somewhere in CONTRIBUTING.md or the syntax documentation or somewhere else about it. I don't really think an issue here works very well as a reminder. (loot/oblivion#20 didn't have any `url` data, for example. I did go and add it before merging the PR, but I had forgotten all about this issue at the time, so this issue neither helped in letting @Felerius know that we would like `url`s added to masterlist entries, nor did it help in reminding me to add it as part of the merge process.)

**Comment by WrinklyNinja** [comment]
Perhaps what would be more helpful would be a style checker that encodes all the info on the Masterlist Editing wiki page and also checks for things like URL data?

**Comment by CurusKeel** [comment]
Forgot that this was still open. Not a huge, deal-breaking issue. Most new additions to the LOOT masterlist also bring along the URLs of the mod anyway. Closing.
