### ISSUE TITLE
Lopad order question

### ISSUE THREAD

**Issue by germanicus1964** [loot/loot.github.io#41]
Why Loot 0.7.1 places new installed mods at the bottom of the load order? And how to change automatic ordering?

**Comment by WrinklyNinja** [comment]
> Why Loot 0.7.1 places new installed mods at the bottom of the load order?

If you're referring to where they are put when you open LOOT, that's because they don't have any existing load order position, so putting them at the end makes more sense than putting them anywhere else.

If you're referring to where they are put when LOOT sorts them, that's just coincidence, LOOT doesn't care whether mods are newly-installed or not when sorting.

As for how to change LOOT's sorting behaviour, read the readme.

**Comment by germanicus1964** [comment]
Thanks for the answer.
