### ISSUE TITLE
Loot Failed

### ISSUE THREAD

**Issue by tornocean** [loot/loot.github.io#48]
exit code 3221225477. Do you know what this means?

**Comment by WrinklyNinja** [comment]
No. Please [provide debug logs](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully).

**Comment by pStyl3** [comment]
I googled that code, these were the two first results:
[APACHE Crashing: Parent: child process exited with status 3221225477 — Restarting](http://stackoverflow.com/questions/10306272/apache-crashing-parent-child-process-exited-with-status-3221225477-restarti)
[Exited with return value 3221225477](http://stackoverflow.com/questions/25679028/exited-with-return-value-3221225477)

Then I searched for LOOT related results:
[2014](http://forums.nexusmods.com/index.php?/topic/473728-mod-organizer/?p=17469004)
[2016](http://forum.step-project.com/topic/9706-mod-step-fix-plugin-order-with-loot-failed-exit-code-3221225477/)

It seems that this issue is a result of LOOT being incorrectly set up within MO (both search result were connected with MO).

**Comment by WrinklyNinja** [comment]
Closing this as invalid. If the issue happens again, please file an issue in the loot/loot repository [issue tracker](https://github.com/loot/loot/issues).
