### ISSUE TITLE
Link to "Tome of xEdit" instead of CreationKit wiki for xEdit cleaning guide?

### ISSUE THREAD

**Issue by Freso** [loot/loot.github.io#69]
We currently link to ["TES5Edit Cleaning Guide - TES5Edit" on the CreationKit wiki](https://www.creationkit.com/index.php?title=TES5Edit_Cleaning_Guide_-_TES5Edit) for guidance on how to clean "dirty" plugins. Recently @Sharlikran has been working on making [Tome of xEdit](https://tes5edit.github.io/docs/) the official comprehensive documentation for xEdit, and it has a section for ["Mod Cleaning and Error Checking"](https://tes5edit.github.io/docs/5-mod-cleaning-and-error-checking.html) (it even has an [abridged description of the cleaning procedure](https://tes5edit.github.io/docs/5-mod-cleaning-and-error-checking.html#Apendix-B)).

Should we link to this guide instead of the CreationKit wiki one? Or should we retain the link to the CreationKit wiki and have *that* link to the Tome?

One benefit of linking directly to the xEdit Tome is that users would also be pointed towards the general documentation for how to use xEdit, since they're already using that.

A downside is that the "cleaning" section isn't the "beginning" of the Tome and in language and tone it generally is directed more to mod authors than mod users.

(@eFrysTon has made some changes in the recent experimental xEdit builds that will change the "xEdit recommended" cleaning procedure too, so this should get reflected probably in both place, but may appear in the official Tome before it reaches the CK wiki. This is not directly related to where we should link though, but may become a factor.)

I'm not personally 100% decided either way, and there might be some in-between options available too, so please be sure to comment your thoughts!

**Comment by WrinklyNinja** [comment]
I think it makes more sense to link to TES5Edit's own docs for instructions on how to do something with TES5Edit. If the cleaning bit of those docs isn't as accessible to mod users, that's a chance to improve them, as it'll benefit more than just our users.

**Comment by Izen-san** [comment]
The primary question is where to point people for the documentation.  This should be the "Tome" because it incorporates the latest developments.  Due to the nature of the web, older docs are going to remain around anyway; but people need to be made aware of the need for the current, updated docs.

The secondary question is regarding the "Cleaning Guide".  This has been an evolutionary process.  Back with Oblivion (and possibly older), it was essential for users to be able to deal with this issue due to the number of mods that had problems with "dirty edits" and how many authors never properly addressed the issue with their mods.  Users had to do so in order to get a stable game.  Over time that has become less of an issue as the modder community became more sensitive to the issue, and some of the "rules of thumb" (such as "ITMs should always be cleaned") have since proven to be less than 100% valid.  Hence the change in focus from "users" to "authors" as the ones who should make the determination of what is required.  But the user community is often not aware of the differences in this regard between different games.  Directing them to an older version of the guide prolongs this confusion.  The newer "Tome" should make the change in reasoning prominent, and if the older guide is still needed, make it an "appendix" or other form of supplemental instruction.

**Comment by Sharlikran** [comment]
The current page for cleaning does have places where it recommends that mod authors clean their own mods.

The tome is the Fallout Training manual with updates to make it more current.

I am not against changing any of the wording that Miax and Justin had where it started that you should not clean other people's mods. More or less that mod authors should do it. However, I dont know how to word it to convey that while it is recommended that mod authors clean their own mods many dont and therefore cleaning mods can be performed by users but that they should test their game to see if it is still stable.

As far as the ck wiki cleaning guide being added as an appendix. I already have the glossary added from the ck wiki. Then there is an abridged cleaning guide that it very straightforward. Other then that I'm not sure what else to retain from the cleaning guide on the ck wiki that isn't already explained.

The xedit docs dont duplicate other guides either. So a user reading the docs understands how to clean files, why, what otms and udrs are and how they effect the game. Leaving it open to others alike alternate to still keep their guide and they dont clash and the time doesn't make those guides obsolete.

**Comment by Sharlikran** [comment]
- [Credits added](https://tes5edit.github.io/docs/index.html)
- [Preface added](https://tes5edit.github.io/docs/5-mod-cleaning-and-error-checking.html)
